name: Gatsby Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.HASUNG_JUN_ACCESS_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
